#!/bin/bash

# pass in multiple files like:
# sh concat_csv.sh ../runs/*/csv/trip*

# use relative path
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output_dir="$script_dir/../data_out"
mkdir -p "$output_dir"

# label the output file with a timestamp
timestamp=$(date +"%Y%m%d_%H%M%S")
filename="${timestamp}.csv"
final_csv="$output_dir/$filename"

# record where the data was concatenated from
sources_file="$output_dir/${timestamp}_Sources"

> "$final_csv"      # overwrite or create the final CSV
> "$sources_file"   # overwrite or create Sources log

# show your work
echo -e "Generated by: $0\n" > "$sources_file"

# loop through every provided dir
first=1
echo "Writing"
for file in "$@"; do
    relpath=$(realpath --relative-to="$script_dir/.." "$file")
    echo -e "\t$relpath"
    echo "$relpath" >> "$sources_file"
    if [[ $first -eq 1 ]]; then
        cat "$file" >> "$final_csv"
        first=0
    else
        tail -n +2 "$file" >> "$final_csv"  # skip header
    fi
done

echo "to $final_csv"
echo "Sources logged in $sources_file"

output_dir="$script_dir/../data_out"
compiled_root="$output_dir/compiled.root"

# Find all root files matching pattern under csv dirs
root_files=()
for dir in "$@"; do
    root_dir="$(realpath "$dir")"
    root_dir="$(dirname "$root_dir")/../root"
    echo "Looking for root files in: $root_dir"
    for file in "$root_dir"/compiled.root; do
        [[ -f "$file" ]] && root_files+=("$file")
    done
done

# Run hadd to merge all collected root files
if [ ${#root_files[@]} -gt 0 ]; then
    hadd -k "$compiled_root" "${root_files[@]}"
else
    echo "No root files found to hadd."
fi

